config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artefacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end

  resources :members

  get 'home/index'

  root to: 'home#index'

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match '/user/confirmation' => 'confirmations#update',
          via: :put, as: :update_user_confirmation
  end

  devise_for :users, controllers: {
    registrations:  'registrations',
    confirmations:  'confirmations',
    sessions:       'milia/sessions',
    passwords:      'milia/passwords'
  }

  match '/plan/edit' => 'tenants#edit',
        via: :get,
        as: :edit_plan

  match '/plan/update' => 'tenants#update',
        via: [:put, :patch],
        as: :update_plan
end

app/models/artefact.rb
# Project artefacts
class Artefact < ActiveRecord::Base
  before_save :upload_to_s3

  attr_accessor :upload

  belongs_to :project

  MAX_FILE_MB   = 10
  MAX_FILE_SIZE = MAX_FILE_MB.megabytes

  validates_presence_of :name, :upload
  validates_uniqueness_of :name

  validate :uploaded_file_size

  private

  def upload_to_s3
    s3 = Aws::S3::Resource.new(region: ENV['S3_REGION'])
    obj = s3.bucket(ENV['S3_BUCKET']).object(file_name)
    obj.upload_file(upload.path, acl: 'public-read')
    self.key = obj.public_url
  end

  def uploaded_file_size
    return unless upload && upload.size >= self.class::MAX_FILE_SIZE

    errors.add(:upload, "File must be less than #{self.class::MAX_FILE_MB}MB")
  end

  def tenant_name
    Tenant.find(Thread.current[:tenant_id]).name.gsub(/\s+|&/, '-')
  end

  def file_name
    "#{tenant_name}/#{upload.original_filename}"
  end
end

app/controllers/artefacts_controller.rb
# Controller for project artefacts
class ArtefactsController < ApplicationController
  before_action :set_artefact, only: [:show, :edit, :update, :destroy]

  # GET /artefacts
  # GET /artefacts.json
  def index
    @artefacts = Artefact.all
  end

  # GET /artefacts/1
  # GET /artefacts/1.json
  def show
  end

  # GET /artefacts/new
  def new
    @artefact = Artefact.new
    @artefact.project_id = params[:project_id]
  end

  # GET /artefacts/1/edit
  def edit
  end

  # POST /artefacts
  # POST /artefacts.json
  def create
    @artefact = Artefact.new(artefact_params)

    respond_to do |format|
      if @artefact.save
        format.html { redirect_to tenant_project_url(tenant_id: Tenant.current_tenant_id,
                                                     id: @artefact.project_id),
                                  notice: 'Artefact was successfully created.' }
        format.json { render :show, status: :created, location: @artefact }
      else
        format.html { render :new }
        format.json { render json: @artefact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artefacts/1
  # PATCH/PUT /artefacts/1.json
  def update
    respond_to do |format|
      if @artefact.update(artefact_params)
        format.html { redirect_to @artefact, notice: 'Artefact was successfully updated.' }
        format.json { render :show, status: :ok, location: @artefact }
      else
        format.html { render :edit }
        format.json { render json: @artefact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artefacts/1
  # DELETE /artefacts/1.json
  def destroy
    @artefact.destroy
    respond_to do |format|
      format.html { redirect_to tenant_project_url(tenant_id: Tenant.current_tenant_id,
                                                   id: @artefact.project_id),
                                notice: 'Artefact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_artefact
    @artefact = Artefact.find(params[:id])
  end

  # Never trust parameters from the internet, only allow the white listed.
  def artefact_params
    params.require(:artefact).permit(:name, :project_id, :upload)
  end
end

app/views/artefacts/_form.html.erb
<%= form_for @artefact, :html => { :class => "form-horizontal artefact" } do |f| %>
  <% if @artefact.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@artefact.errors.count, "error") %> prohibited this artefact from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @artefact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :upload, value: 'File to upload', :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :upload, :class => 'form-control' %>
    </div>
  </div>

  <%= f.hidden_field :project_id %>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            tenant_project_path(tenant_id: Tenant.current_tenant_id, id: @artefact.project_id),
            :class => 'btn btn-default' %>
<% end %>

app/views/artefacts/_list.html.erb
<%- model_class = Artefact -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% artefacts.each do |artefact| %>
      <tr>
        <td><%= link_to artefact.name, artefact, class: 'main-link' %></td>
        <td><%= s3_link Tenant.current_tenant_id, artefact.key %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      artefact_path(artefact),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New artefact', new_artefact_path(project_id: @project.id),
            :class => 'btn btn-primary' %>

app/views/artefacts/edit.html.erb
<%- model_class = Artefact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artefacts/index.html.erb
<%- model_class = Artefact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= render 'artefacts/list', artfeacts: @project.artefacts %>

app/views/artefacts/new.html.erb
<%- model_class = Artefact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artefacts/show.html.erb
<%- model_class = Artefact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @artefact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @artefact.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @artefact.project_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              artefacts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_artefact_path(@artefact), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              artefact_path(@artefact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>